[KERNEL]
"KERNEL/kernel.nex"


[PROGRAMS]
shell = "KERNEL/shell.nex"
snake = "programs/misc/snake.nex"
bmpviewer = "programs/misc/bmp_viewer.nex"


[FILES]
text-file = "files/text_file.txt"
bmp_image = "files/tree_small.bmp"