[KERNEL]
"KERNEL/kernel.nex"


[PROGRAMS]
hello_world = "programs/print.bin"
comp_test = "programs/compiler_test_1.bin"
color_viewer = "programs/color_viewer.bin"

[FILES]
text-file = "files/text_file.txt"