[KERNEL]
"KERNEL/kernel.nex"


[PROGRAMS]
shell = "KERNEL/shell.nex"
snake = "programs/misc/snake.nex"
bmpviewer = "programs/misc/bmp_viewer.nex"
zelda = "programs/misc/zelda.nex"
gpu = "programs/tests/gpu_0.nesm"


[FILES]
text-file = "files/text_file.txt"
bmp-image = "files/tree_small.bmp"
